services:
  api:
    build: ./apps/api
    ports: ["3000:3000"]
    container_name: fipe-api-bootcamp

  web:
    build: ./apps/web
    ports: ["8080:80"]
    environment:
      - VITE_API_URL=http://api:3000
    depends_on:
      - api
    container_name: fipe-web-bootcamp